## Numpy = numerical + python
- 다차원배열(multi-dimensional array) 라이브러리로 과학,공학 연산을 쉽게 지원한다 : numpy의 주요객체는  homogeneous multidimensional array 

- 대규모 배열처리를 쉽게함

- ndarray(다차원배열)라는 자료를 생성하고 이를 바탕으로 색인, 처리, 연산 등을 하는 기능을 수행

- 간단한 기술통계 분석 정도는 가능하지만 실제로는 Scipy, Pandas, matplotlib 등 다른 Python 패키지와 함께 쓰이는 경우가 많다.

#### 특징
- python list보다 빠르고 메모리효율좋음

- 내부에 연속된 메모리구조를 가지고(Array Interface)를 가지고 있고, C를 통해 연산된다.



### 1.생성함수
### arange, ones, zeros, empty, _like

In [22]:
import numpy as np


In [23]:
arr1 = np.zeros(5)
arr2 = np.zeros((3,2))
arr3 = np.zeros((3,3,3))
arr3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
arr = np.ones(5)
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#초기화되지 않은값으로 배열생성, 메모리초기화안되어서 예상못한 쓰레기값으로 배열생성
arr3 = np.empty(5) 
arr3

array([0., 0., 0., 0., 0.])

In [26]:
a = np.array([1,2,3,4])
a[:3]
#슬라이싱가능
a[:3] = 1
a
#슬라이싱한 부분 일괄 수정가능 -> python에선 안됨
# arr[:3] = 1
#     ~~~^^^^
# TypeError: can only assign an iterable



array([1, 1, 1, 4])

In [27]:
# something_like
# _like는 지정된 array의 shape 크기만큼 지정된 값으로 채워 array를 반환합니다.
# 앞에서 정리한 ones, zeros, empty를 사용할 수 있습니다.
test_matrix = np.arange(30).reshape(5,6)
np.empty_like(test_matrix)
np.ones_like(test_matrix)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### arange : 원하는 숫자범위 간격에따른 array생성

In [28]:
# arange()활용
print(np.arange(10))
print(np.arange(10)+1)
print(np.arange(10)/2)
print(np.arange(10)*2)
print(np.arange(10)%2)

#arange() 실수가능
print(np.arange(0.1, 1.1, 0.1))
#타입 지정가능
print(np.arange(0.1, 1.1, 0.1,dtype=int))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  2  4  6  8 10 12 14 16 18]
[0 1 0 1 0 1 0 1 0 1]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0 0 0 0 0 0 0 0 0 0]


In [29]:
#rank 1-100등까지 등수가 담긴 array생성
rank = np.random.choice(np.arange(1,101), size=100)

# 1  ~ 20:  1
# 21 ~ 40:  2
# 41 ~ 60:  3
# 61 ~ 80:  4
# 81 ~ 100: 5
# 의 값을 부여

(rank-1)//20 +1

#for문으로도가능

array([3, 5, 4, 3, 2, 3, 2, 1, 1, 5, 4, 5, 1, 1, 2, 2, 2, 3, 5, 2, 4, 2,
       5, 2, 5, 3, 5, 1, 4, 3, 1, 2, 2, 4, 3, 2, 3, 5, 5, 2, 2, 4, 4, 2,
       1, 1, 4, 1, 1, 5, 3, 5, 1, 2, 1, 2, 1, 4, 1, 4, 3, 3, 1, 5, 4, 1,
       1, 4, 1, 1, 3, 2, 1, 4, 4, 2, 3, 4, 4, 3, 1, 4, 1, 4, 4, 3, 1, 4,
       1, 4, 2, 4, 5, 1, 5, 5, 5, 2, 5, 3])

In [30]:
a1 = np.random.randint(1,101,size = 100)  #지정한 범위 내에서 무작위로 정수를 생성 (중복가능)


a2 = np.random.choice(np.arange(1,101),size = 100 ,replace = True) #중복허용해서 범위내 100개선택
a3 = np.random.choice(np.arange(1,101),size = 100 ,replace = False) #중복없이 범위내 100개선택

### linspace
arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

In [31]:
a = np.linspace(2,3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함

## 랜덤배열생성
#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```
#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [32]:
np.random.random(size=(2, 3))
np.random.randint(0, 10, size=(3, 2))

array([[0, 7],
       [3, 7],
       [1, 5]])

### 로또1등 당첨프로그램(-)


In [33]:
# 함수 만들기
# 함수의 입력은 복권 구매 금액
# 금액에 맞는 복권 매수 구매
# 복권은 자동
# 1등 번호는 6, 11, 16, 19, 21, 32
# 복권 번호는 1 ~ 45

    



### 변환함수
### 배열형태변환

In [34]:
#1차원배열 2차원배열로변환
arr = np.array([1,2,3,4,5,6])
arr2 = arr.reshape(2,3)
arr2

#2차원배열 1차원으로
arr1 = arr2.flatten()
arr1

array([1, 2, 3, 4, 5, 6])

In [35]:
#타입변환
#정수를 실수로
arr_int = np.array([1,2,3])
arr_flaot = arr_int.astype(float)
arr_flaot


#문자열 배열을 정수형 배열로 변환
arr_str = np.array(['1', '2', '3'])
arr_int = arr_str.astype(int)
print(arr_int)

[1 2 3]


In [36]:
#축변환
a = np.array([[1,2],[3,4],[5,6]])
trans = a.transpose()
trans

array([[1, 3, 5],
       [2, 4, 6]])

In [37]:
#집계함수
a.sum()
a.mean()
a.std()
a.min()
a.max()
a.argmax() #index반환(평탄화했을때)
# a.argmin() #index반환


5

In [38]:
#논리함수
arr1 = np.array([True, False, False, True])
arr2 = np.array([True, True, False, False])

np.logical_and(arr1, arr2)
np.logical_or(arr1, arr2)
np.logical_not(arr1)
np.logical_not(arr2)

array([False, False,  True,  True])

In [39]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1+arr2
arr1-arr2
arr1*arr2
arr1*2
arr1/arr2
arr1**3
arr1>20

array([False, False,  True,  True])

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]
a[(a % 2) == 0]
a[1]
a[:2]

array([1, 2])

### 숙제
- 10x10배열에서 서로 다른 두 원소를 선택해서 두 원소의 차이의 절대값이 가장 작은 두 원소를 찾아보기

- 두 원소의 차이의 절대값이 가장 큰 두 원소를 찾아보기

In [112]:
arr = np.random.rand(10,10)
arr = arr.flatten()



min =  arr.max()- arr.min()
sorted_arr = np.sort(arr)
min_idx = 0
for i in range(len(sorted_arr)-1):
  diff = sorted_arr[i] -sorted_arr[i+1]
  
  if diff < 0:
    diff *= -1
  if diff < min:
    min = diff
    min_idx = i  
print(f'첫번째:{sorted_arr[i]}, 두번째: {sorted_arr[i+1]}')    



첫번째:0.9835203984217912, 두번째: 0.9968287191997748
